# Generated by Django 5.2.5 on 2025-08-15 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='O nome de usuário deve ter no mínimo 4 caracteres.')])),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('bio', models.TextField(blank=True, max_length=1012, null=True, verbose_name='Biografia')),
                ('website', models.URLField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de Perfil')),
                ('phone', models.CharField(blank=True, help_text='Número de telefone/celular', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter entre 9 e 15 dígitos.', regex='^\\d{9,15}$')], verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Moderador')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super Administrador')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_user_email'), models.UniqueConstraint(fields=('username',), name='unique_user_username')],
            },
        ),
    ]
