# Generated by Django 5.2.5 on 2025-08-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
                'db_table': 'about',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contacts',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, default='Olá, meu nome é', max_length=255, null=True, verbose_name='Saudação')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título profissional')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
                'db_table': 'hero',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'messages',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Palavras-chave')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Metadado',
                'verbose_name_plural': 'Metadados',
                'db_table': 'metadata',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.BooleanField(default=True, verbose_name="Exibir 'Sobre mim'")),
                ('projects', models.BooleanField(default=True, verbose_name='Exibir projetos')),
                ('skills', models.BooleanField(default=True, verbose_name='Exibir habilidades')),
                ('process', models.BooleanField(default=True, verbose_name='Exibir processo')),
                ('contact', models.BooleanField(default=True, verbose_name='Exibir contato')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Ícone (HTML ou classe CSS)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'skills',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do grupo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de habilidades',
                'verbose_name_plural': 'Grupos de habilidades',
                'db_table': 'skill_groups',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_items', to='core.contact')),
            ],
            options={
                'verbose_name': 'Item de informação',
                'verbose_name_plural': 'Itens de informação',
                'db_table': 'info_items',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagem')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='URL da demonstração')),
                ('source_url', models.URLField(blank=True, default='https://github.com/', null=True, verbose_name='Código-fonte')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_index', models.IntegerField(blank=True, null=True, verbose_name='Ordem de exibição')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('skill', models.ManyToManyField(blank=True, to='core.skill')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projects',
                'ordering': ['ordering_index', '-created'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.skillgroup'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='core.contact')),
            ],
            options={
                'verbose_name': 'Link social',
                'verbose_name_plural': 'Links sociais',
                'db_table': 'social_links',
                'ordering': ['title'],
            },
        ),
    ]
