# Generated by Django 5.2.5 on 2025-08-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto de copyright')),
            ],
            options={
                'verbose_name': 'Rodapé',
                'verbose_name_plural': 'Rodapés',
                'db_table': 'footers',
            },
        ),
    ]
